#!/usr/bin/env node

var glob = require('glob').Glob;
var path = require('path');
var lib = {};

new glob('./library/Ubui/*', null, function (a, b) {
	b.forEach(function (a) {
		console.log('+ ' + a);
		lib[path.basename(a)] = require(a);
	});
	
});